// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaOrderingApplication.Models;

namespace MVCPIzzaOrderingApplication.Migrations
{
    [DbContext(typeof(pizzaContext))]
    partial class pizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaOrderingApplication.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DelivaryCharges")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.OrderDetail", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaNumber")
                        .HasColumnType("int");

                    b.HasKey("ItemNumber")
                        .HasName("PK__OrderDet__C28ACDB6EC11E389");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaNumber");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.OrderItemDetail", b =>
                {
                    b.Property<int>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<int>("ToppingNumber")
                        .HasColumnType("int");

                    b.HasKey("ItemNumber", "ToppingNumber")
                        .HasName("PK__OrderIte__F23F4C4294D5BFFF");

                    b.HasIndex("ToppingNumber");

                    b.ToTable("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.PizzaDetail", b =>
                {
                    b.Property<int>("PizzaNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PizzaName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("PizzaPrice")
                        .HasColumnType("int");

                    b.Property<string>("PizzaType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PizzaNumber")
                        .HasName("PK__PizzaDet__E4FE0B3038219213");

                    b.ToTable("PizzaDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.Topping", b =>
                {
                    b.Property<int>("ToppingNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ToppingName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ToppingPrice")
                        .HasColumnType("int");

                    b.HasKey("ToppingNumber")
                        .HasName("PK__Toppings__0B581F426950E5DA");

                    b.ToTable("Toppings");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.UserLoginDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserMail")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("UserId")
                        .HasName("PK__UserLogi__1788CC4CF747A498");

                    b.ToTable("UserLoginDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.Order", b =>
                {
                    b.HasOne("PizzaOrderingApplication.Models.UserLoginDetail", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Orders__UserId__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.OrderDetail", b =>
                {
                    b.HasOne("PizzaOrderingApplication.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__Order__3F466844");

                    b.HasOne("PizzaOrderingApplication.Models.PizzaDetail", "PizzaNumberNavigation")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PizzaNumber")
                        .HasConstraintName("FK__OrderDeta__Pizza__403A8C7D");

                    b.Navigation("Order");

                    b.Navigation("PizzaNumberNavigation");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.OrderItemDetail", b =>
                {
                    b.HasOne("PizzaOrderingApplication.Models.OrderDetail", "ItemNumberNavigation")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ItemNumber")
                        .HasConstraintName("FK__OrderItem__ItemN__4316F928")
                        .IsRequired();

                    b.HasOne("PizzaOrderingApplication.Models.Topping", "ToppingNumberNavigation")
                        .WithMany("OrderItemDetails")
                        .HasForeignKey("ToppingNumber")
                        .HasConstraintName("FK__OrderItem__Toppi__440B1D61")
                        .IsRequired();

                    b.Navigation("ItemNumberNavigation");

                    b.Navigation("ToppingNumberNavigation");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.OrderDetail", b =>
                {
                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.PizzaDetail", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.Topping", b =>
                {
                    b.Navigation("OrderItemDetails");
                });

            modelBuilder.Entity("PizzaOrderingApplication.Models.UserLoginDetail", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
